# ==============================================================
# = Articoli Web Service con Autenticazione JWT
# ==============================================================

server:
  port: 8081

