
spring.application.name=HelloWorldSpringCloudResilience4j-1


management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health

