
spring.application.name=HelloWorldSpringCloudResilience4j-2


management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health


# 2 req ogni 5 sec
resilience4j.ratelimiter.instances.default.limitForPeriod =2
resilience4j.ratelimiter.instances.default.limitRefreshPeriod=5s

resilience4j.ratelimiter.instances.default.timeOutDuration=0


resilience4j.bulkhead.instances.default.MaxConcurrentCalls=2


