spring.application.name=HelloWorldSpringCloudResilience4j
server.port = 8081


resilience4j.retry.instances.esempio.maxAttempts=5 
resilience4j.retry.instances.esempio.waitDuration: 1s
#resilience4j.retry.instances.esempio.enableExponentialBackoff=true